food/urls.py
from django.urls import path

from . import views

app_name = "food"
urlpatterns = [
    #/food/ url for ClasBaseView
    path('',views.IndexClassView.as_view(), name='index'),
    #/food/ url for functional base view
    # path("", views.index, name="index"),
    #/food/1
    path("item/", views.item, name="item"),
    #detail view functional base view
    # path("<int:item_id>/", views.detail, name="detail"),
    #detail view classBaseview
    path('<int:pk>/',views.FoodDetail.as_view(),name='detail'),
    #add item functioal baseView
    # path('add',views.create_item, name='create_item'),
    #add item classBaseview
    path('add',views.CreateItem.as_view(),name='create_item'),
    #edit item_desc
    path('update/<int:id>/',views.update_item,name='update_item'),
    #delete
    path('delete/<int:id>/',views.delete_item,name='delete_item'),
]

food_app/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views  as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('food.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),


]

urlpatterns +=[

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Item(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://jeffs-burger.ch/wp-content/uploads/2020/12/gst-default-placeholder-4-1024x1024.jpg")
    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse('food:detail', kwargs={'pk':self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile_pictures/default2.png', upload_to='profile_pictures')
    location = models.CharField(max_length=100,)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms

from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["item_name", "item_desc", "item_price", "item_image"]

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

food/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template import loader
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from .forms import ItemForm
from .models import Item

# Create your views here.


def index(request):
    item_list = Item.objects.all()
    context = {
        "item_list": item_list,
    }
    return render(request, "food/index.html", context)


class IndexClassView(ListView):
    model = Item
    template_name = "food/index.html"
    context_object_name = "item_list"


def item(request):
    return HttpResponse("<h1> this is the item view </h1>")


# def detail(request, item_id):
#     item = Item.objects.get(pk=item_id)
#     context = {
#         "item": item,
#     }
#
#     return render(request, "food/detail.html", context)

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'
    


# def create_item(request):
#     form = ItemForm(request.POST or None)
#
#     if form.is_valid():
#         form.save()
#         return redirect("food:index")
#     context = {
#         "form": form,
#     }
#     return render(request, "food/item-form.html", context)

#this is classBaseview for create item
class CreateItem(CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']
    template_name = 'food/item-form.html'
    success_url = reverse_lazy('food:index')
    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)


def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect("food:index")
    return render(request, "food/item-form.html", {"form": form, "item": item})


def delete_item(request, id):
    item = Item.objects.get(id=id)
    if request.method == "POST":
        item.delete()
        return redirect("food:index")
    return render(
        request,
        "food/item-delete.html",
        {
            "item": item,
        },
    )

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'wlecome {username}, your account is created')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request,'users/register.html',{
    'form':form,
    })

@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

     <lin rel='stylesheet' href="{% static 'food/style.css' %}"
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">FoodApp</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'food:create_item' %}">Add Item</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
      </ul>
      <span class="navbar-text">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'profile' %}">Profile<span class="sr-only"></span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'logout' %}">Logout<span class="sr-only">(current)</span></a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </span>
    </div>
  </nav>
  {% if messages %}
  {% for message in messages %}
  <div class="alert" alert-{{message.tags }}>
    {{message}}
  </div>

  {% endfor %}
  {% endif %}
  {% block body %}


    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}


{% block body%}

<div class="conatiner">
  <div class="row">
    <div class="col-md-6">
      <img height="300px" src="{{item.item_image}}" class="card">
    </div>
    <div class="col-md-6">
      <h1>{{object.item_name}}</h1>
      <h1>{{object.item_desc}}</h1>
      <h1>{{object.item_price}}</h1>
      <a href="{% url 'food:delete_item' item.id %}"> Delete</a>
    </div>
  </div>

</div>



{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}


{% block body %}

{% for item in item_list %}
<div class="row">
  <div class="col-md-3 offset-md-2">
    <img class="card" height="150px" src="{{ item.item_image }}" alt="">
  </div>
  <div class="col-md-4 ">
    <h3>{{item.item_name}}</h3>
    <h5>{{item.item_desc}}</h5>
    <h6>{{item.item_price}}</h6>
  </div>
  <div class="col-md-2">
    <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
  </div>

</div>
{% endfor %}

{% endblock %}

food/templates/food/item-delete.html
<form class="" action="" method="POST">
  {% csrf_token %}
  <h2> Are you sur you want to delete  {{item.item_name }}</h2>
  <button type="submit" name="button">Confirm</button>
</form>

food/templates/food/item-form.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card">
        <div class="card-header bg-info">
          <div class="card-title text-white">
            Add Item
          </div>

        </div>
        <div class="card-body">
          <form class="" action="#" method="POST">
            {% csrf_token %}
            
            {{form}}
            <button class="btn-info" type="submit" name="button">Save</button>
          </form>
        </div>
      </div>
    </div>
  </div>

</div>

{% endblock %}


<form class="" action="" method="Post">
  {% csrf_token %}
  {{form}}
  <button type="submit" name="button">Save</button>
</form>

users/templates/users/login.html
{% extends 'food/base.html' %}



{% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card">
        <div class="card-header bg-info">
          <div class="card-title text-white">
            Login
          </div>

        </div>
        <div class="card-body">
          <form class="" action="#" method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                  {{ field.name}}
                  {{field}}
                </div>
            {% endfor%}
            <button class="btn-info" type="submit" name="button">Login</button>
          </form>
        </div>
      </div>
    </div>
  </div>

</div>

{% endblock  %}

users/templates/users/logout.html
<h1> you have been logged out successfully  </h1>

<a href="{% url 'login' %}">Login</a>

users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img width="100px" height="100px" src="{{user.profile.image.url }}" alt="">

users/templates/users/register.html
{% extends 'food/base.html' %}



{% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <div class="card">
        <div class="card-header bg-info">
          <div class="card-title text-white">
            Register
          </div>

        </div>
        <div class="card-body">
          <form class="" action="#" method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                  {{ field.name}}
                  <br>
                  {{field}}
                </div>
            {% endfor%}
            <button class="btn-info" type="submit" name="button">Login</button>
          </form>
        </div>
      </div>
    </div>
  </div>

</div>

{% endblock  %}